# Generated by Django 5.2.17 on 2026-08-30 18:54

import apps.members.models
import core.encryption
import django.db.models.deletion
import sorl.thumbnail.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Full Name')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('profile_picture', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=apps.members.models.member_upload_to, validators=[core.encryption.validate_file_size], verbose_name='Profile Picture')),
                ('status', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'INACTIVE'), (3, 'SUSPENDED')], default=1, verbose_name='Status')),
                ('joined', models.DateField(blank=True, null=True)),
                ('archived', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='LoginAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True)),
                ('device', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_audits', to='members.member', verbose_name='Member')),
            ],
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('bank', models.IntegerField(choices=[(1, 'Maybank (Malayan Banking Berhad)'), (2, 'CIMB Bank'), (3, 'Public Bank'), (4, 'RHB Bank'), (5, 'Hong Leong Bank'), (6, 'Ambank'), (7, 'Bank Islam Malaysia'), (8, 'Bank Rakyat'), (9, 'Affin Bank'), (10, 'Alliance Bank'), (11, 'UOB (United Overseas Bank)'), (12, 'HSBC Bank'), (13, 'Standard Chartered Bank'), (14, 'OCBC Bank'), (15, 'Citibank'), (16, 'Agrobank'), (17, 'Bank Muamalat'), (18, 'BSN (Bank Simpanan Nasional)'), (19, 'Big Pay'), (20, 'Touch N Go'), (21, 'GX Bank')], verbose_name='Bank')),
                ('account_holder_name', models.CharField(max_length=150, verbose_name='Account Holder Name')),
                ('account_number', models.CharField(max_length=64, verbose_name='Account Number')),
                ('is_primary', models.BooleanField(default=True)),
                ('archived', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='members.member', verbose_name='Member')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('platform', models.IntegerField(choices=[(1, 'INSTAGRAM'), (2, 'TIKTOK')], verbose_name='Platform')),
                ('handle', models.CharField(max_length=150, verbose_name='Handle')),
                ('profile_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Profile Url')),
                ('is_verified', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('archived', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_accounts', to='members.member', verbose_name='Member')),
            ],
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['created'], name='members_mem_created_12cb74_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['status'], name='members_mem_status_734de0_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['phone_number'], name='members_mem_phone_n_28ee55_idx'),
        ),
        migrations.AddIndex(
            model_name='loginaudit',
            index=models.Index(fields=['created'], name='members_log_created_0de107_idx'),
        ),
        migrations.AddIndex(
            model_name='bankdetail',
            index=models.Index(fields=['created'], name='members_ban_created_26b6dd_idx'),
        ),
        migrations.AddIndex(
            model_name='bankdetail',
            index=models.Index(fields=['is_primary'], name='members_ban_is_prim_03e740_idx'),
        ),
        migrations.AddIndex(
            model_name='platformaccount',
            index=models.Index(fields=['created'], name='members_pla_created_a73708_idx'),
        ),
        migrations.AddIndex(
            model_name='platformaccount',
            index=models.Index(fields=['platform'], name='members_pla_platfor_6642d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='platformaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('archived__isnull', True)), fields=('member', 'platform'), name='unique_active_platform_per_member'),
        ),
    ]
