# Generated by Django 5.2.17 on 2026-09-16 19:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_role_member_role_role_members_rol_created_4ba1cf_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('status', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'INACTIVE')], default=1, verbose_name='Status')),
                ('archived', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='user_groups', to='members.member', verbose_name='Members')),
            ],
            options={
                'indexes': [models.Index(fields=['created'], name='members_use_created_881247_idx'), models.Index(fields=['name'], name='members_use_name_4461fe_idx')],
            },
        ),
    ]
