# Generated by Django 5.2.17 on 2026-08-30 18:54

import apps.front_view.models
import core.encryption
import django.db.models.deletion
import sorl.thumbnail.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=apps.front_view.models.banner_upload_to, validators=[core.encryption.validate_file_size], verbose_name='Banner Image')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link')),
                ('location', models.IntegerField(choices=[(1, 'HOME BANNER'), (2, 'EVENT BANNER'), (3, 'POST OF THE DAY')], default=1, verbose_name='Location')),
                ('active_from', models.DateTimeField(blank=True, null=True, verbose_name='Active From')),
                ('active_until', models.DateTimeField(blank=True, null=True, verbose_name='Active Until')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Ordering')),
                ('archived', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created'], name='front_view__created_21a78d_idx'), models.Index(fields=['location'], name='front_view__locatio_dced64_idx')],
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('location', models.IntegerField(choices=[(1, 'HOME'), (2, 'MISSION TODAY'), (3, 'EARNING'), (4, 'MISSED'), (5, 'RULES'), (6, 'LEADERBOARD'), (7, 'JOB BOARD'), (8, 'AFFILIATE LINKS'), (9, 'PROFILE'), (10, 'BANK DETAILS')], verbose_name='Location')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Ordering')),
                ('archived', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['location'], name='front_view__locatio_4a128e_idx')],
            },
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('category', models.IntegerField(choices=[(1, 'EARNINGS'), (2, 'LEADERBOARD'), (3, 'JOB')], unique=True, verbose_name='Category')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terms and Conditions',
                'verbose_name_plural': 'Terms and Conditions',
                'indexes': [models.Index(fields=['category'], name='front_view__categor_b92ab2_idx')],
            },
        ),
    ]
