# Generated by Django 5.2.17 on 2026-10-07 04:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_view', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyInfluencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('phone_number', models.CharField(blank=True, default='', max_length=30, verbose_name='Phone Number')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Deposit Amount')),
                ('reg_count', models.PositiveIntegerField(default=0, verbose_name='Registrations')),
                ('cvs_count', models.PositiveIntegerField(default=0, verbose_name='Conversions')),
                ('archived', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created'], name='front_view__created_447c84_idx')],
            },
        ),
    ]
