# Generated by Django 5.2.17 on 2026-10-08 05:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_view', '0002_dummy_influencer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('slot', models.IntegerField(choices=[(1, 'NIGHT'), (2, 'DAY')], verbose_name='Slot')),
                ('status', models.IntegerField(choices=[(1, 'SUCCESS'), (2, 'FAILED')], verbose_name='Status')),
                ('attempt', models.PositiveSmallIntegerField(default=1, verbose_name='Attempt')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='Row Count')),
                ('not_found', models.JSONField(blank=True, default=list, verbose_name='Not Found')),
                ('error', models.TextField(blank=True, default='', verbose_name='Error')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InfluencerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(verbose_name='Rank')),
                ('member_uuid', models.CharField(max_length=36, verbose_name='Member Uuid')),
                ('full_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Full Name')),
                ('phone_number', models.CharField(blank=True, default='', max_length=30, verbose_name='Phone Number')),
                ('reg_count', models.PositiveIntegerField(default=0)),
                ('cvs_count', models.PositiveIntegerField(default=0)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Deposit Amount')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='front_view.influencersyncrun', verbose_name='Run')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.AddIndex(
            model_name='influencersyncrun',
            index=models.Index(fields=['created'], name='front_view__created_6d191c_idx'),
        ),
        migrations.AddIndex(
            model_name='influencersyncrun',
            index=models.Index(fields=['status', 'created'], name='front_view__status_6987b3_idx'),
        ),
        migrations.AddIndex(
            model_name='influencersnapshot',
            index=models.Index(fields=['run', 'rank'], name='front_view__run_id_7de3e2_idx'),
        ),
        migrations.AddIndex(
            model_name='influencersnapshot',
            index=models.Index(fields=['run', 'phone_number'], name='front_view__run_id_ed772a_idx'),
        ),
    ]
