# Generated by Django 5.2.17 on 2026-08-30 18:54

import apps.jobs.models
import core.encryption
import django.db.models.deletion
import sorl.thumbnail.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crmadmin', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('logo', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=apps.jobs.models.company_upload_to, validators=[core.encryption.validate_file_size], verbose_name='Logo')),
                ('telegram_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Telegram Group Link')),
                ('status', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'INACTIVE')], default=1, verbose_name='Status')),
                ('archived', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('recurrence', models.IntegerField(choices=[(1, 'DAILY'), (2, 'WEEKLY'), (3, 'MONTHLY')], default=1, verbose_name='Recurrence')),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Payment Amount')),
                ('payment_period', models.IntegerField(choices=[(1, 'DAILY'), (2, 'WEEKLY'), (3, 'MONTHLY')], default=3, verbose_name='Payment Period')),
                ('deduction_per_miss', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Deduction Per Miss')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('status', models.IntegerField(choices=[(1, 'DRAFT'), (2, 'ACTIVE'), (3, 'PAUSED'), (4, 'COMPLETED')], default=1, verbose_name='Status')),
                ('archived', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='jobs.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('platform', models.IntegerField(choices=[(1, 'INSTAGRAM'), (2, 'TIKTOK')], verbose_name='Platform')),
                ('content_type', models.IntegerField(choices=[(1, 'REEL'), (2, 'STORY'), (3, 'POST'), (4, 'VIDEO')], verbose_name='Content Type')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Quantity')),
                ('archived', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='jobs.job', verbose_name='Job')),
            ],
        ),
        migrations.CreateModel(
            name='JobSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('singleton_enforcer', models.BooleanField(default=True, unique=True)),
                ('default_deduction_per_miss', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Default Deduction Per Miss')),
                ('default_payment_period', models.IntegerField(choices=[(1, 'DAILY'), (2, 'WEEKLY'), (3, 'MONTHLY')], default=3, verbose_name='Default Payment Period')),
                ('submission_grace_hours', models.PositiveIntegerField(default=0, verbose_name='Submission Grace Hours')),
                ('requires_review', models.BooleanField(default=True, verbose_name='Requires Review')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Maintenance Mode')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Settings',
                'verbose_name_plural': 'Job Settings',
            },
        ),
        migrations.CreateModel(
            name='MemberJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'APPLIED'), (2, 'ACTIVE'), (3, 'COMPLETED'), (4, 'REJECTED')], default=1, verbose_name='Status')),
                ('affiliate_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Affiliate Link')),
                ('affiliate_link_status', models.IntegerField(choices=[(1, 'PENDING'), (2, 'SUBMITTED'), (3, 'ACTIVE'), (4, 'PAUSED')], default=1, verbose_name='Affiliate Link Status')),
                ('joined', models.DateField(blank=True, null=True)),
                ('completed', models.DateField(blank=True, null=True)),
                ('archived', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_jobs', to='jobs.job', verbose_name='Job')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_jobs', to='members.member', verbose_name='Member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('period_key', models.CharField(max_length=20, verbose_name='Period Key')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('proof_link', models.URLField(blank=True, max_length=500, null=True)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to=apps.jobs.models.proof_upload_to, validators=[core.encryption.validate_file_size])),
                ('note', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(blank=True, null=True)),
                ('comments', models.PositiveIntegerField(blank=True, null=True)),
                ('shares', models.PositiveIntegerField(blank=True, null=True)),
                ('metrics_screenshot', models.FileField(blank=True, null=True, upload_to=apps.jobs.models.proof_upload_to, validators=[core.encryption.validate_file_size])),
                ('metrics_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
                ('member_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='jobs.memberjob', verbose_name='Member Job')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='jobs.jobrequirement', verbose_name='Requirement')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tasks', to='crmadmin.admin', verbose_name='Reviewed By')),
            ],
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.jobs.models.content_upload_to, validators=[core.encryption.validate_content_file_size])),
                ('media_type', models.IntegerField(choices=[(1, 'VIDEO'), (2, 'PHOTO')], verbose_name='Media Type')),
                ('original_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Original Name')),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('archived', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='jobs.membertask', verbose_name='Task')),
            ],
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['created'], name='jobs_compan_created_a67eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['status'], name='jobs_compan_status_353d9c_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created'], name='jobs_job_created_a99b91_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='jobs_job_status_7d017a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['start_date', 'end_date'], name='jobs_job_start_d_f278cc_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrequirement',
            index=models.Index(fields=['created'], name='jobs_jobreq_created_a915a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobrequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('archived__isnull', True)), fields=('job', 'platform', 'content_type'), name='unique_active_requirement_per_job'),
        ),
        migrations.AddIndex(
            model_name='memberjob',
            index=models.Index(fields=['created'], name='jobs_member_created_fd55fe_idx'),
        ),
        migrations.AddIndex(
            model_name='memberjob',
            index=models.Index(fields=['status'], name='jobs_member_status_388b19_idx'),
        ),
        migrations.AddConstraint(
            model_name='memberjob',
            constraint=models.UniqueConstraint(condition=models.Q(('archived__isnull', True)), fields=('member', 'job'), name='unique_active_member_job'),
        ),
        migrations.AddIndex(
            model_name='membertask',
            index=models.Index(fields=['created'], name='jobs_member_created_633241_idx'),
        ),
        migrations.AddIndex(
            model_name='membertask',
            index=models.Index(fields=['period_key'], name='jobs_member_period__7494dc_idx'),
        ),
        migrations.AddIndex(
            model_name='membertask',
            index=models.Index(fields=['period_end'], name='jobs_member_period__63a943_idx'),
        ),
        migrations.AddIndex(
            model_name='membertask',
            index=models.Index(fields=['submitted_at'], name='jobs_member_submitt_248e78_idx'),
        ),
        migrations.AddIndex(
            model_name='membertask',
            index=models.Index(fields=['reviewed_at'], name='jobs_member_reviewe_7f39a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='membertask',
            constraint=models.UniqueConstraint(fields=('member_job', 'requirement', 'period_key'), name='unique_task_per_period'),
        ),
        migrations.AddIndex(
            model_name='taskfile',
            index=models.Index(fields=['created'], name='jobs_taskfi_created_962ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='taskfile',
            index=models.Index(fields=['media_type'], name='jobs_taskfi_media_t_bba85a_idx'),
        ),
    ]
