# Generated by Django 5.2.17 on 2026-09-03 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfile',
            name='frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendered_files', to='frames.frame', verbose_name='Frame'),
        ),
        migrations.AddField(
            model_name='taskfile',
            name='is_original',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskfile',
            name='render_status',
            field=models.IntegerField(blank=True, choices=[(1, 'PROCESSING'), (2, 'DONE'), (3, 'FAILED')], null=True, verbose_name='Render Status'),
        ),
        migrations.AddIndex(
            model_name='taskfile',
            index=models.Index(fields=['frame'], name='jobs_taskfi_frame_i_8ca27e_idx'),
        ),
    ]
