# Generated by Django 5.2.17 on 2026-09-03 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_taskfile_frame_taskfile_is_original_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='taskfile',
            name='jobs_taskfi_frame_i_8ca27e_idx',
        ),
        migrations.RemoveField(
            model_name='taskfile',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='taskfile',
            name='is_original',
        ),
        migrations.RemoveField(
            model_name='taskfile',
            name='render_status',
        ),
        migrations.AddField(
            model_name='job',
            name='script',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Script'),
        ),
    ]
