# Generated by Django 5.2.17 on 2026-09-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_taskfile_jobs_taskfi_frame_i_8ca27e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membertask',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='membertask',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='membertask',
            name='shares',
        ),
        migrations.RemoveField(
            model_name='membertask',
            name='views',
        ),
    ]
