# Generated by Django 5.2.17 on 2026-09-18 05:17

import apps.koc.models
import core.encryption
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_usergroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('content_file', models.FileField(upload_to=apps.koc.models.submission_upload_to, validators=[core.encryption.validate_content_file_size], verbose_name='Content File')),
                ('media_type', models.IntegerField(choices=[(1, 'VIDEO'), (2, 'PHOTO')], verbose_name='Media Type')),
                ('published_url', models.URLField(max_length=500, verbose_name='Published Reel Link')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koc_submissions', to='members.member', verbose_name='Member')),
            ],
            options={
                'indexes': [models.Index(fields=['created'], name='koc_submiss_created_6e5f20_idx'), models.Index(fields=['member'], name='koc_submiss_member__00779b_idx')],
            },
        ),
    ]
