# Generated by Django 5.2.17 on 2026-08-30 18:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('period_key', models.CharField(max_length=20, verbose_name='Period Key')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount')),
                ('note', models.TextField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('archived', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='members.member', verbose_name='Member')),
            ],
            options={
                'indexes': [models.Index(fields=['created'], name='earnings_pa_created_1c105e_idx'), models.Index(fields=['period_key'], name='earnings_pa_period__06584d_idx'), models.Index(fields=['paid_at'], name='earnings_pa_paid_at_27f43f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('archived__isnull', True)), fields=('member', 'period_key'), name='unique_active_payout_per_period')],
            },
        ),
    ]
