# Generated by Django 5.2.17 on 2026-08-30 18:54

import apps.admins.models
import core.encryption
import django.db.models.deletion
import sorl.thumbnail.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Full Name')),
                ('status', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'INACTIVE')], default=1, verbose_name='Status')),
                ('profile_picture', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=apps.admins.models.admin_upload_to, validators=[core.encryption.validate_file_size], verbose_name='Profile Picture')),
                ('archived', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('activity', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='admins.admin', verbose_name='Admin')),
            ],
        ),
        migrations.AddIndex(
            model_name='admin',
            index=models.Index(fields=['created'], name='admins_admi_created_05a178_idx'),
        ),
        migrations.AddIndex(
            model_name='admin',
            index=models.Index(fields=['status'], name='admins_admi_status_c1e13a_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created'], name='admins_acti_created_32312c_idx'),
        ),
    ]
