# Generated by Django 5.2.17 on 2026-08-30 18:54

import apps.frames.models
import core.encryption
import django.db.models.deletion
import sorl.thumbnail.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to=apps.frames.models.frame_upload_to, validators=[core.encryption.validate_file_size, core.encryption.validate_transparent_image], verbose_name='Frame Image')),
                ('aspect_ratio', models.IntegerField(choices=[(1, '9:16'), (2, '1:1'), (3, '4:5')], default=1, verbose_name='Aspect Ratio')),
                ('media_type', models.IntegerField(choices=[(1, 'BOTH'), (2, 'VIDEO'), (3, 'PHOTO')], default=1, verbose_name='Media Type')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Ordering')),
                ('status', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'INACTIVE')], default=1, verbose_name='Status')),
                ('archived', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='jobs.job', verbose_name='Job')),
            ],
            options={
                'indexes': [models.Index(fields=['created'], name='frames_fram_created_4c8cf6_idx'), models.Index(fields=['status'], name='frames_fram_status_3eac8b_idx'), models.Index(fields=['media_type'], name='frames_fram_media_t_f6647f_idx')],
            },
        ),
    ]
