# Generated by Django 5.2.17 on 2026-09-03 21:11

import apps.frames.models
import core.encryption
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('original_file', models.FileField(upload_to=apps.frames.models.rendered_content_upload_to, validators=[core.encryption.validate_content_file_size])),
                ('media_type', models.IntegerField(choices=[(1, 'VIDEO'), (2, 'PHOTO')], verbose_name='Media Type')),
                ('original_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Original Name')),
                ('rendered_file', models.FileField(blank=True, null=True, upload_to=apps.frames.models.rendered_content_upload_to)),
                ('render_status', models.IntegerField(choices=[(1, 'PROCESSING'), (2, 'DONE'), (3, 'FAILED')], default=1, verbose_name='Render Status')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renders', to='frames.frame', verbose_name='Frame')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendered_content', to='members.member', verbose_name='Member')),
            ],
            options={
                'indexes': [models.Index(fields=['created'], name='frames_rend_created_f4a825_idx'), models.Index(fields=['frame'], name='frames_rend_frame_i_be2a4c_idx'), models.Index(fields=['member'], name='frames_rend_member__9d8156_idx')],
            },
        ),
    ]
