# Generated by Django 5.2.17 on 2026-09-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0002_renderedcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='renderedcontent',
            name='crop_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='renderedcontent',
            name='crop_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='renderedcontent',
            name='crop_x',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='renderedcontent',
            name='crop_y',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='renderedcontent',
            name='trim_in',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='renderedcontent',
            name='trim_out',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
