# Generated by Django 5.2.17 on 2026-09-16 19:26

import apps.frames.models
import core.encryption
import django.db.models.deletion
import sorl.thumbnail.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0004_alter_renderedcontent_crop_x_and_more'),
        ('jobs', '0004_remove_membertask_comments_remove_membertask_likes_and_more'),
        ('members', '0003_usergroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='background',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=apps.frames.models.frame_upload_to, validators=[core.encryption.validate_file_size], verbose_name='Background Image'),
        ),
        migrations.CreateModel(
            name='FrameAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'INACTIVE')], default=1, verbose_name='Status')),
                ('archived', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='frames.frame', verbose_name='Frame')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frame_assignments', to='jobs.job', verbose_name='Job')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frame_assignments', to='members.member', verbose_name='Member')),
                ('user_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frame_assignments', to='members.usergroup', verbose_name='User Group')),
            ],
            options={
                'indexes': [models.Index(fields=['created'], name='frames_fram_created_41647a_idx'), models.Index(fields=['status'], name='frames_fram_status_6a2c25_idx'), models.Index(fields=['frame', 'status'], name='frames_fram_frame_i_5f49c8_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('job__isnull', False), ('member__isnull', True), ('user_group__isnull', True)), models.Q(('job__isnull', True), ('member__isnull', False), ('user_group__isnull', True)), models.Q(('job__isnull', True), ('member__isnull', True), ('user_group__isnull', False)), _connector='OR'), name='frame_assignment_single_target')],
            },
        ),
    ]
