# Generated by Django 5.2.17 on 2026-09-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0005_frame_background_frameassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='job',
        ),
    ]
