# Generated by Django 5.2.17 on 2026-09-16 19:40

import apps.frames.models
import core.encryption
import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0006_remove_frame_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=apps.frames.models.frame_upload_to, validators=[core.encryption.validate_file_size, core.encryption.validate_transparent_image], verbose_name='Frame Image'),
        ),
    ]
