# Generated by Django 5.2.17 on 2026-09-16 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0007_alter_frame_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='frame_type',
            field=models.IntegerField(choices=[(1, 'JOB'), (2, 'POSTDESK')], default=1, verbose_name='Frame Type'),
        ),
        migrations.AddIndex(
            model_name='frame',
            index=models.Index(fields=['frame_type'], name='frames_fram_frame_t_5d6e00_idx'),
        ),
    ]
