# Generated by Django 5.2.17 on 2026-09-17 16:29

import apps.frames.models
import core.encryption
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0008_frame_frame_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('original_file', models.FileField(blank=True, null=True, upload_to=apps.frames.models.rendered_content_upload_to, validators=[core.encryption.validate_content_file_size])),
                ('media_type', models.IntegerField(blank=True, choices=[(1, 'VIDEO'), (2, 'PHOTO')], null=True, verbose_name='Media Type')),
                ('original_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Original Name')),
                ('pull_status', models.IntegerField(choices=[(1, 'PROCESSING'), (2, 'DONE'), (3, 'FAILED')], default=1, verbose_name='Pull Status')),
                ('pull_failure_reason', models.CharField(blank=True, default='', max_length=500)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='renderedcontent',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='renderedcontent',
            name='original_file',
        ),
        migrations.RemoveField(
            model_name='renderedcontent',
            name='original_name',
        ),
    ]
