# Generated by Django 5.2.17 on 2026-09-17 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0009_sourcevideo_remove_renderedcontent_media_type_and_more'),
        ('members', '0003_usergroup'),
        ('third_party', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcevideo',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pulled_videos', to='third_party.thirdpartyconnection', verbose_name='Connection'),
        ),
        migrations.AddField(
            model_name='sourcevideo',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sourcevideo',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_videos', to='members.member', verbose_name='Member'),
        ),
        migrations.AddField(
            model_name='renderedcontent',
            name='source_video',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='renders', to='frames.sourcevideo', verbose_name='Source Video'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='renderedcontent',
            index=models.Index(fields=['source_video'], name='frames_rend_source__4958aa_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcevideo',
            index=models.Index(fields=['created'], name='frames_sour_created_f1a9b6_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcevideo',
            index=models.Index(fields=['member'], name='frames_sour_member__fbd462_idx'),
        ),
    ]
