# Generated by Django 5.2.17 on 2026-09-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0010_sourcevideo_connection_sourcevideo_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renderedcontent',
            name='caption_background_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='renderedcontent',
            name='caption_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='renderedcontent',
            name='caption_font_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='renderedcontent',
            name='caption_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='renderedcontent',
            name='caption_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='renderedcontent',
            name='caption_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
