# Generated by Django 5.2.17 on 2026-09-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0012_renderedcontent_caption_reference_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renderedcontent',
            name='overlay_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='renderedcontent',
            name='overlay_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='renderedcontent',
            name='overlay_zoom',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
