# Generated by Django 5.2.17 on 2026-09-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0013_renderedcontent_overlay_x_renderedcontent_overlay_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcevideo',
            name='pull_duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
