# Generated by Django 5.2.17 on 2026-09-03 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('role', models.IntegerField(choices=[(1, 'ADMIN'), (2, 'MEMBER')], verbose_name='Recipient Role')),
                ('notification_type', models.IntegerField(choices=[(1, 'JOB_POSTED'), (2, 'TASK_ASSIGNED'), (3, 'TASK_SUBMITTED'), (4, 'TASK_APPROVED'), (5, 'TASK_REJECTED')], verbose_name='Type')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('message', models.CharField(blank=True, max_length=500, null=True, verbose_name='Message')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_user', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['created'], name='notificatio_created_5feed0_idx'), models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_564b1f_idx')],
            },
        ),
    ]
