# Generated by Django 5.2.17 on 2026-09-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'JOB_POSTED'), (2, 'TASK_ASSIGNED'), (3, 'TASK_SUBMITTED'), (4, 'TASK_APPROVED'), (5, 'TASK_REJECTED'), (6, 'RENDER_READY')], verbose_name='Type'),
        ),
    ]
