# Generated by Django 5.2.17 on 2026-09-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'JOB_POSTED'), (2, 'TASK_ASSIGNED'), (3, 'TASK_SUBMITTED'), (4, 'TASK_APPROVED'), (5, 'TASK_REJECTED'), (6, 'RENDER_READY'), (7, 'APPLICATION_APPROVED'), (8, 'APPLICATION_REJECTED'), (9, 'RESULT_PENDING'), (10, 'RESULT_COMPLETED'), (11, 'KOC_SUBMISSION'), (12, 'FRAME_ASSIGNED'), (13, 'SOURCE_VIDEO_READY'), (14, 'SOURCE_VIDEO_FAILED')], verbose_name='Type'),
        ),
    ]
